/**
 * Custom Style Dictionary formats for Swift / SwiftUI output.
 */

function hexOnly(hex) {
  return hex.replace('#', '').toUpperCase();
}

function camelCase(path) {
  return path
    .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
    .join('');
}

function pascalCase(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function fontWeightToSwift(weight) {
  const map = {
    325: '.regular',
    400: '.regular',
    500: '.medium',
    600: '.semibold',
    700: '.bold',
  };
  return map[weight] || `.init(rawValue: ${weight})`;
}

/**
 * swift/wldColorDefaults – Generates extension WLDColor with static let constants.
 * Matches the existing `WLDColor+Defaults.swift` pattern.
 */
export const swiftColorDefaults = {
  name: 'swift/wldColorDefaults',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter((t) => t.$type === 'color');

    const lines = tokens.map((token) => {
      const name = camelCase(token.path);
      const hex = hexOnly(token.$value || token.value);
      return `    static let ${name} = WLDColor("${hex}")`;
    });

    return [
      'import Foundation',
      '',
      '// Generated by World Design System – do not edit manually',
      'extension WLDColor {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * swift/wldColorTheme – Generates a struct (LightTheme / DarkTheme) with
 * hex string constants for semantic colors.
 */
export const swiftColorTheme = {
  name: 'swift/wldColorTheme',
  format: ({ dictionary, options }) => {
    const structName = options.structName || 'LightTheme';
    const tokens = dictionary.allTokens.filter(
      (t) => t.$type === 'color' && t.path[0] === 'semantic',
    );

    const lines = tokens.map((token) => {
      const name = camelCase(token.path.slice(1));
      const hex = hexOnly(token.$value || token.value);
      return `    static let ${name} = WLDColor("${hex}")`;
    });

    return [
      'import Foundation',
      '',
      `// Generated by World Design System – do not edit manually`,
      `enum ${structName} {`,
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * swift/wldFontDefaults – Generates extension WLDFont with static let constants.
 * Matches the existing `WLDFont+Defaults.swift` pattern.
 */
export const swiftFontDefaults = {
  name: 'swift/wldFontDefaults',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter(
      (t) => t.$type === 'typography',
    );

    const lines = tokens.map((token) => {
      const name = token.path[token.path.length - 1];
      const v = token.$value || token.value;
      return `    public static let ${name} = WLDFont(size: ${v.fontSize}, weight: ${v.fontWeight}, letterSpacing: ${v.letterSpacing}, lineHeight: ${v.lineHeightMultiplier})`;
    });

    return [
      'import Foundation',
      '',
      '// Generated by World Design System – do not edit manually',
      'extension WLDFont {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * swift/spacing – Generates spacing enum with CGFloat constants.
 */
export const swiftSpacing = {
  name: 'swift/spacing',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter(
      (t) => t.$type === 'dimension' && t.path[0] === 'spacing',
    );

    const lines = tokens.map((token) => {
      const name = token.path[token.path.length - 1];
      const v = token.$value ?? token.value;
      return `    static let ${name}: CGFloat = ${v}`;
    });

    return [
      'import CoreGraphics',
      '',
      '// Generated by World Design System – do not edit manually',
      'public enum WDSSpacing {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * swift/components – Generates component tokens (border radius, buttons, shadows).
 */
export const swiftComponents = {
  name: 'swift/components',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter(
      (t) => t.path[0] === 'component',
    );

    const sections = [];

    // Border radius
    const radiusTokens = tokens.filter((t) => t.path[1] === 'borderRadius');
    if (radiusTokens.length) {
      sections.push('    // MARK: - Border Radius');
      radiusTokens.forEach((t) => {
        const name = t.path[t.path.length - 1];
        const v = t.$value ?? t.value;
        sections.push(
          `    static let borderRadius${pascalCase(name)}: CGFloat = ${v}`,
        );
      });
      sections.push('');
    }

    // Buttons
    const buttonTokens = tokens.filter((t) => t.path[1] === 'button');
    if (buttonTokens.length) {
      sections.push('    // MARK: - Button Sizes');
      buttonTokens.forEach((t) => {
        const size = t.path[2];
        const prop = t.path[3];
        const v = t.$value ?? t.value;
        sections.push(
          `    static let button${pascalCase(size)}${pascalCase(prop)}: CGFloat = ${v}`,
        );
      });
      sections.push('');
    }

    // Shadows
    const shadowTokens = tokens.filter((t) => t.path[1] === 'shadow');
    if (shadowTokens.length) {
      sections.push('    // MARK: - Shadows');
      shadowTokens.forEach((t) => {
        const name = t.path[2];
        const v = t.$value ?? t.value;
        sections.push(
          `    static let shadow${pascalCase(name)} = WDSShadow(`,
          `        color: "${hexOnly(v.color)}",`,
          `        alpha: ${v.alpha},`,
          `        offsetX: ${v.offsetX},`,
          `        offsetY: ${v.offsetY},`,
          `        blur: ${v.blur},`,
          `        cornerRadius: ${v.cornerRadius}`,
          '    )',
        );
      });
    }

    return [
      'import CoreGraphics',
      '',
      '// Generated by World Design System – do not edit manually',
      'public struct WDSShadow {',
      '    public let color: String',
      '    public let alpha: Double',
      '    public let offsetX: CGFloat',
      '    public let offsetY: CGFloat',
      '    public let blur: CGFloat',
      '    public let cornerRadius: CGFloat',
      '}',
      '',
      'public enum WDSComponents {',
      ...sections,
      '}',
      '',
    ].join('\n');
  },
};
