/**
 * Custom Style Dictionary formats for Swift / SwiftUI output.
 *
 * All generated types are standalone – no dependency on WLDColor or WLDFont.
 * Colors are raw hex strings; typography is a plain WdsFontSpec struct.
 * The consuming app bridges these to its own platform types.
 */

function hexOnly(hex) {
  return hex.replace('#', '').toUpperCase();
}

function camelCase(path) {
  return path
    .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
    .join('');
}

function pascalCase(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * swift/wldColorDefaults – Standalone WDSColorPalette with String hex constants.
 */
export const swiftColorDefaults = {
  name: 'swift/wldColorDefaults',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter((t) => t.$type === 'color');

    const lines = tokens.map((token) => {
      const name = camelCase(token.path);
      const hex = hexOnly(token.$value || token.value);
      return `    public static let ${name} = "${hex}"`;
    });

    return [
      'import Foundation',
      '',
      '// Generated by World Design System – do not edit manually',
      'public enum WdsColorPalette {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * swift/wldColorTheme – Standalone LightTheme / DarkTheme with String hex constants.
 */
export const swiftColorTheme = {
  name: 'swift/wldColorTheme',
  format: ({ dictionary, options }) => {
    const structName = options.structName || 'WdsLightColorTokens';
    const tokens = dictionary.allTokens.filter(
      (t) => t.$type === 'color' && t.path[0] === 'semantic',
    );

    const lines = tokens.map((token) => {
      const name = camelCase(token.path.slice(1));
      const hex = hexOnly(token.$value || token.value);
      return `    public static let ${name} = "${hex}"`;
    });

    return [
      'import Foundation',
      '',
      `// Generated by World Design System – do not edit manually`,
      `public enum ${structName} {`,
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * swift/wldFontDefaults – Standalone WdsTypography with WdsFontSpec values.
 */
export const swiftFontDefaults = {
  name: 'swift/wldFontDefaults',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter(
      (t) => t.$type === 'typography',
    );

    const lines = tokens.map((token) => {
      const name = token.path[token.path.length - 1];
      const v = token.$value || token.value;
      return `    public static let ${name} = WdsFontSpec(size: ${v.fontSize}, weight: ${v.fontWeight}, letterSpacing: ${v.letterSpacing}, lineHeight: ${v.lineHeightMultiplier})`;
    });

    return [
      'import Foundation',
      '',
      '// Generated by World Design System – do not edit manually',
      'public struct WdsFontSpec: Sendable {',
      '    public let size: Double',
      '    public let weight: Int',
      '    public let letterSpacing: Double',
      '    public let lineHeight: Double',
      '}',
      '',
      'public enum WdsTypography {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * swift/spacing – Spacing enum with CGFloat constants.
 */
export const swiftSpacing = {
  name: 'swift/spacing',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens.filter(
      (t) => t.$type === 'dimension' && t.path[0] === 'spacing',
    );

    const lines = tokens.map((token) => {
      const name = token.path[token.path.length - 1];
      const v = token.$value ?? token.value;
      return `    public static let ${name}: CGFloat = ${v}`;
    });

    return [
      'import CoreGraphics',
      '',
      '// Generated by World Design System – do not edit manually',
      'public enum WdsSpacing {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};