import CoreGraphics

// Generated by World Design System – do not edit manually
public struct WDSShadow {
    public let color: String
    public let alpha: Double
    public let offsetX: CGFloat
    public let offsetY: CGFloat
    public let blur: CGFloat
    public let cornerRadius: CGFloat
}

public enum WDSComponents {
    // MARK: - Border Radius
    static let borderRadiusXs: CGFloat = 4
    static let borderRadiusSm: CGFloat = 6
    static let borderRadiusMd: CGFloat = 10
    static let borderRadiusLg: CGFloat = 12
    static let borderRadiusFull: CGFloat = 9999

    // MARK: - Button Sizes
    static let buttonSmallHeight: CGFloat = 44
    static let buttonSmallCornerRadius: CGFloat = 16
    static let buttonNormalHeight: CGFloat = 56
    static let buttonNormalCornerRadius: CGFloat = 16
    static let buttonNavBarHeight: CGFloat = 36
    static let buttonNavBarCornerRadius: CGFloat = 16
    static let buttonSlimHeight: CGFloat = 40
    static let buttonSlimCornerRadius: CGFloat = 16

    // MARK: - Shadows
    static let shadowStandard = WDSShadow(
        color: "002466",
        alpha: 0.1,
        offsetX: 0,
        offsetY: 10,
        blur: 30,
        cornerRadius: 12
    )
    static let shadowMinimal = WDSShadow(
        color: "002466",
        alpha: 0.1,
        offsetX: 0,
        offsetY: 2,
        blur: 10,
        cornerRadius: 12
    )
}
