import CoreGraphics

// Generated by World Design System – do not edit manually
public struct WDSShadow: Sendable {
    public let color: String
    public let alpha: Double
    public let offsetX: CGFloat
    public let offsetY: CGFloat
    public let blur: CGFloat
    public let cornerRadius: CGFloat
}

public enum WDSComponents {
    // MARK: - Border Radius
    public static let borderRadiusXs: CGFloat = 4
    public static let borderRadiusSm: CGFloat = 6
    public static let borderRadiusMd: CGFloat = 10
    public static let borderRadiusLg: CGFloat = 12
    public static let borderRadiusFull: CGFloat = 9999

    // MARK: - Button Sizes
    public static let buttonSmallHeight: CGFloat = 44
    public static let buttonSmallCornerRadius: CGFloat = 16
    public static let buttonNormalHeight: CGFloat = 56
    public static let buttonNormalCornerRadius: CGFloat = 16
    public static let buttonNavBarHeight: CGFloat = 36
    public static let buttonNavBarCornerRadius: CGFloat = 16
    public static let buttonSlimHeight: CGFloat = 40
    public static let buttonSlimCornerRadius: CGFloat = 16

    // MARK: - Shadows
    public static let shadowStandard = WDSShadow(
        color: "002466",
        alpha: 0.1,
        offsetX: 0,
        offsetY: 10,
        blur: 30,
        cornerRadius: 12
    )
    public static let shadowMinimal = WDSShadow(
        color: "002466",
        alpha: 0.1,
        offsetX: 0,
        offsetY: 2,
        blur: 10,
        cornerRadius: 12
    )
}
