import Foundation

// Generated by World Design System – do not edit manually
enum DarkTheme {
    static let backgroundPrimary = WLDColor("181818")
    static let backgroundSecondary = WLDColor("3C424B")
    static let backgroundTertiary = WLDColor("717680")
    static let textPrimary = WLDColor("FFFFFF")
    static let textSecondary = WLDColor("B1B8C2")
    static let textTertiary = WLDColor("838D9B")
    static let textInverse = WLDColor("181818")
    static let borderDefault = WLDColor("3C424B")
    static let borderStrong = WLDColor("717680")
    static let actionPrimary = WLDColor("FFFFFF")
    static let actionPrimaryContent = WLDColor("181818")
    static let actionSecondary = WLDColor("3C424B")
    static let actionDisabled = WLDColor("3C424B")
    static let actionDisabledContent = WLDColor("717680")
    static let statusError = WLDColor("F7503F")
    static let statusWarning = WLDColor("FFB833")
    static let statusSuccess = WLDColor("33D167")
    static let statusInfo = WLDColor("3385FF")
    static let tabBarSelected = WLDColor("FFFFFF")
    static let tabBarUnselected = WLDColor("838D9B")
    static let tabBarBackground = WLDColor("181818")
    static let tabBarBorder = WLDColor("3C424B")
}
