import Foundation

// Generated by World Design System – do not edit manually
public enum DarkTheme {
    public static let backgroundPrimary = "181818"
    public static let backgroundSecondary = "3C424B"
    public static let backgroundTertiary = "717680"
    public static let textPrimary = "FFFFFF"
    public static let textSecondary = "B1B8C2"
    public static let textTertiary = "838D9B"
    public static let textInverse = "181818"
    public static let borderDefault = "3C424B"
    public static let borderStrong = "717680"
    public static let actionPrimary = "FFFFFF"
    public static let actionPrimaryContent = "181818"
    public static let actionSecondary = "3C424B"
    public static let actionDisabled = "3C424B"
    public static let actionDisabledContent = "717680"
    public static let statusError = "F7503F"
    public static let statusWarning = "FFB833"
    public static let statusSuccess = "33D167"
    public static let statusInfo = "3385FF"
    public static let tabBarSelected = "FFFFFF"
    public static let tabBarUnselected = "838D9B"
    public static let tabBarBackground = "181818"
    public static let tabBarBorder = "3C424B"
}
