import Foundation

// Generated by World Design System – do not edit manually
enum LightTheme {
    static let backgroundPrimary = WLDColor("FFFFFF")
    static let backgroundSecondary = WLDColor("F9FAFB")
    static let backgroundTertiary = WLDColor("F3F4F5")
    static let textPrimary = WLDColor("181818")
    static let textSecondary = WLDColor("717680")
    static let textTertiary = WLDColor("9BA3AE")
    static let textInverse = WLDColor("FFFFFF")
    static let borderDefault = WLDColor("EBECEF")
    static let borderStrong = WLDColor("D6D9DD")
    static let actionPrimary = WLDColor("181818")
    static let actionPrimaryContent = WLDColor("FFFFFF")
    static let actionSecondary = WLDColor("F3F4F5")
    static let actionDisabled = WLDColor("EBECEF")
    static let actionDisabledContent = WLDColor("9BA3AE")
    static let statusError = WLDColor("F2280D")
    static let statusWarning = WLDColor("FFAE00")
    static let statusSuccess = WLDColor("00C230")
    static let statusInfo = WLDColor("005CFF")
    static let tabBarSelected = WLDColor("181818")
    static let tabBarUnselected = WLDColor("838D9B")
    static let tabBarBackground = WLDColor("FFFFFF")
    static let tabBarBorder = WLDColor("EBECEF")
}
