import Foundation

// Generated by World Design System – do not edit manually
extension WLDFont {
    public static let d1 = WLDFont(size: 56, weight: 600, letterSpacing: -0.02, lineHeight: 1.2)
    public static let n1 = WLDFont(size: 44, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let n2 = WLDFont(size: 34, weight: 600, letterSpacing: -0.02, lineHeight: 1.2)
    public static let n3 = WLDFont(size: 30, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let n4 = WLDFont(size: 26, weight: 600, letterSpacing: -0.02, lineHeight: 1.2)
    public static let n5 = WLDFont(size: 19, weight: 600, letterSpacing: -0.02, lineHeight: 1.2)
    public static let h1 = WLDFont(size: 34, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let h2 = WLDFont(size: 30, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let h3 = WLDFont(size: 26, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let h4 = WLDFont(size: 20, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let s1 = WLDFont(size: 19, weight: 500, letterSpacing: 0, lineHeight: 1.2)
    public static let s2 = WLDFont(size: 17, weight: 500, letterSpacing: 0, lineHeight: 1.2)
    public static let s3 = WLDFont(size: 15, weight: 500, letterSpacing: 0, lineHeight: 1.2)
    public static let s4 = WLDFont(size: 12, weight: 500, letterSpacing: 0, lineHeight: 1.2)
    public static let l1 = WLDFont(size: 17, weight: 600, letterSpacing: 0, lineHeight: 1.2)
    public static let l2 = WLDFont(size: 15, weight: 600, letterSpacing: 0, lineHeight: 1.2)
    public static let l3 = WLDFont(size: 13, weight: 600, letterSpacing: 0, lineHeight: 1.2)
    public static let b1 = WLDFont(size: 19, weight: 325, letterSpacing: 0, lineHeight: 1.3)
    public static let b2 = WLDFont(size: 17, weight: 325, letterSpacing: 0, lineHeight: 1.3)
    public static let b3 = WLDFont(size: 15, weight: 325, letterSpacing: 0, lineHeight: 1.3)
    public static let b4 = WLDFont(size: 13, weight: 325, letterSpacing: 0, lineHeight: 1.3)
}
