import Foundation

// Generated by World Design System – do not edit manually
public struct WDSFontSpec: Sendable {
    public let size: Double
    public let weight: Int
    public let letterSpacing: Double
    public let lineHeight: Double
}

public enum WDSTypography {
    public static let d1 = WDSFontSpec(size: 56, weight: 600, letterSpacing: -0.02, lineHeight: 1.2)
    public static let n1 = WDSFontSpec(size: 44, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let n2 = WDSFontSpec(size: 34, weight: 600, letterSpacing: -0.02, lineHeight: 1.2)
    public static let n3 = WDSFontSpec(size: 30, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let n4 = WDSFontSpec(size: 26, weight: 600, letterSpacing: -0.02, lineHeight: 1.2)
    public static let n5 = WDSFontSpec(size: 19, weight: 600, letterSpacing: -0.02, lineHeight: 1.2)
    public static let h1 = WDSFontSpec(size: 34, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let h2 = WDSFontSpec(size: 30, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let h3 = WDSFontSpec(size: 26, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let h4 = WDSFontSpec(size: 20, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let s1 = WDSFontSpec(size: 19, weight: 500, letterSpacing: 0, lineHeight: 1.2)
    public static let s2 = WDSFontSpec(size: 17, weight: 500, letterSpacing: 0, lineHeight: 1.2)
    public static let s3 = WDSFontSpec(size: 15, weight: 500, letterSpacing: 0, lineHeight: 1.2)
    public static let s4 = WDSFontSpec(size: 12, weight: 500, letterSpacing: 0, lineHeight: 1.2)
    public static let l1 = WDSFontSpec(size: 17, weight: 600, letterSpacing: 0, lineHeight: 1.2)
    public static let l2 = WDSFontSpec(size: 15, weight: 600, letterSpacing: 0, lineHeight: 1.2)
    public static let l3 = WDSFontSpec(size: 13, weight: 600, letterSpacing: 0, lineHeight: 1.2)
    public static let b1 = WDSFontSpec(size: 19, weight: 325, letterSpacing: 0, lineHeight: 1.3)
    public static let b2 = WDSFontSpec(size: 17, weight: 325, letterSpacing: 0, lineHeight: 1.3)
    public static let b3 = WDSFontSpec(size: 15, weight: 325, letterSpacing: 0, lineHeight: 1.3)
    public static let b4 = WDSFontSpec(size: 13, weight: 325, letterSpacing: 0, lineHeight: 1.3)
}
