import Foundation

// Generated by World Design System – do not edit manually
public enum WdsLightColorTokens {
    public static let backgroundPrimary = "FFFFFF"
    public static let backgroundSecondary = "F9FAFB"
    public static let backgroundTertiary = "F3F4F5"
    public static let textPrimary = "181818"
    public static let textSecondary = "717680"
    public static let textTertiary = "9BA3AE"
    public static let textInverse = "FFFFFF"
    public static let borderDefault = "EBECEF"
    public static let borderStrong = "D6D9DD"
    public static let actionPrimary = "181818"
    public static let actionPrimaryContent = "FFFFFF"
    public static let actionSecondary = "F3F4F5"
    public static let actionDisabled = "EBECEF"
    public static let actionDisabledContent = "9BA3AE"
    public static let statusError = "F2280D"
    public static let statusWarning = "FFAE00"
    public static let statusSuccess = "00C230"
    public static let statusInfo = "005CFF"
    public static let tabBarSelected = "181818"
    public static let tabBarUnselected = "838D9B"
    public static let tabBarBackground = "FFFFFF"
    public static let tabBarBorder = "EBECEF"
}
