import Foundation

// Generated by World Design System – do not edit manually
public struct WdsFontSpec: Sendable {
    public let size: Double
    public let weight: Int
    public let letterSpacing: Double
    public let lineHeight: Double
}

public enum WdsTypography {
    public static let d1 = WdsFontSpec(size: 56, weight: 600, letterSpacing: -0.02, lineHeight: 1.2)
    public static let n1 = WdsFontSpec(size: 44, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let n2 = WdsFontSpec(size: 34, weight: 600, letterSpacing: -0.02, lineHeight: 1.2)
    public static let n3 = WdsFontSpec(size: 30, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let n4 = WdsFontSpec(size: 26, weight: 600, letterSpacing: -0.02, lineHeight: 1.2)
    public static let n5 = WdsFontSpec(size: 19, weight: 600, letterSpacing: -0.02, lineHeight: 1.2)
    public static let h1 = WdsFontSpec(size: 34, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let h2 = WdsFontSpec(size: 30, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let h3 = WdsFontSpec(size: 26, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let h4 = WdsFontSpec(size: 20, weight: 600, letterSpacing: -0.01, lineHeight: 1.2)
    public static let s1 = WdsFontSpec(size: 19, weight: 500, letterSpacing: 0, lineHeight: 1.2)
    public static let s2 = WdsFontSpec(size: 17, weight: 500, letterSpacing: 0, lineHeight: 1.2)
    public static let s3 = WdsFontSpec(size: 15, weight: 500, letterSpacing: 0, lineHeight: 1.2)
    public static let s4 = WdsFontSpec(size: 12, weight: 500, letterSpacing: 0, lineHeight: 1.2)
    public static let l1 = WdsFontSpec(size: 17, weight: 600, letterSpacing: 0, lineHeight: 1.2)
    public static let l2 = WdsFontSpec(size: 15, weight: 600, letterSpacing: 0, lineHeight: 1.2)
    public static let l3 = WdsFontSpec(size: 13, weight: 600, letterSpacing: 0, lineHeight: 1.2)
    public static let b1 = WdsFontSpec(size: 19, weight: 325, letterSpacing: 0, lineHeight: 1.3)
    public static let b2 = WdsFontSpec(size: 17, weight: 325, letterSpacing: 0, lineHeight: 1.3)
    public static let b3 = WdsFontSpec(size: 15, weight: 325, letterSpacing: 0, lineHeight: 1.3)
    public static let b4 = WdsFontSpec(size: 13, weight: 325, letterSpacing: 0, lineHeight: 1.3)
}
